# Generated by Django 5.1.4 on 2025-01-20 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumeauditing', '0002_uploadedresume_suggestions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedresume',
            old_name='files',
            new_name='file',
        ),
    ]
