# Generated by Django 5.1.4 on 2025-04-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedInOptimization', '0002_remove_linkedinprofile_certifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
