# Generated by Django 5.1.4 on 2025-04-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedInOptimization', '0003_certification_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinprofile',
            name='location',
            field=models.CharField(default='pokhara', max_length=100),
        ),
    ]
