# Generated by Django 5.1.4 on 2025-01-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('contactNo', models.CharField(max_length=10)),
                ('address', models.CharField(default='pokhara', max_length=100)),
                ('summary', models.TextField()),
            ],
        ),
    ]
