# Generated by Django 5.1.4 on 2025-01-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='skills',
        ),
        migrations.AddField(
            model_name='resume',
            name='address',
            field=models.CharField(default='pokhara', max_length=100),
        ),
        migrations.DeleteModel(
            name='Education',
        ),
    ]
