# Generated by Django 5.1.4 on 2025-04-09 14:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='Email',
            field=models.EmailField(help_text='Professional email address', max_length=254),
        ),
        migrations.AlterField(
            model_name='resume',
            name='address',
            field=models.TextField(help_text='Your complete address'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='contactNo',
            field=models.CharField(help_text='10-digit phone number', max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator('^[0-9]*$', 'Only numbers are allowed.')]),
        ),
        migrations.AlterField(
            model_name='resume',
            name='fullName',
            field=models.CharField(help_text='Your full name as you want it on your resume', max_length=100, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='summary',
            field=models.TextField(help_text='Brief overview of your professional background (3-5 sentences)', verbose_name='Professional Summary'),
        ),
    ]
